# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of Orlo.W
email: ow.cc@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yaozong.wang" # the base hostname & protocol for your site
twitter_username:  orlowang
github_username:   owcc
facebook_username: orlo.wang
weibo_username:    orlowang
author:            Orlo Wang

# highlighter: pygments

# Build settings
markdown: kramdown

defaults:
- scope:
    path: ""
    type: posts
  values:
    author: Orlo Wang
- scope:
    path: _posts/tattle
    type: posts
  values:
    layout: post
    category: tattle
- scope:
    path: _posts/project
    type: posts
  values:
    layout: post
    category: project
- scope:
    path: _posts/technology
    type: posts
  values:
    layout: post
    category: technology

permalink: /docs/:year/:month/:day/:title

